### ISSUE TITLE
texto para la página de presentación.

### ISSUE THREAD

**Issue by meetsCode** [meetsCode/meetsCode.github.io#1]
Estoy escribiendo en la rama desarrollo un texto para poder poner en la página de inicio.
Si sergi quiere que cada párrafo vaya en un fichero distinto para que él pueda crear una página más dinámica solo tiene que pedirlo.
En breves segundo envío la primera versión.

**Comment by meetsCode** [comment]
Ah! sergi no te olvides de poner un enlace a las diapositivas de 
[slideShare](https://www.slideshare.net/luissnchezpea)
 
De momento es todo lo que tenemos.

Puedes ponerle el encabezado como "las diapositivas de nuestra puesta de largo en Infarma-Innova"

**Comment by DataKatebet** [comment]
He leído el texto nuevo. Por ahora, para tener algo para estos tres días, sólo pondría los tres primeros párrafos. Las explicaciones posteriores (reglamento delegado, blockchain, etc) están bien, pero todavía el texto no está armónico. Prometo mirarlo estos días para que podamos dar por cuasi-finiquitado el tema de la página de presentación, los textos no se me dan mal. 

Me voy a la farma, cambio y fuera por hoy!

**Comment by sia-x** [comment]
La web ya está subida en la url (tracbox.io sin www, estoy trabajando en ello). Partes a comentar:

- Todo el texto y donde se encuentra decid posibles mejoras

- En el botón del principio donde pone Ventajas es donde irá el blog

- En el apartado El Proyecto no se que imagen poner, he dejado la que venia de la plantilla

- En ventajas mejoraré la imagen de fondo, la tengo que editar con photoshop para que los iconos sean los que nos interesan más

- En el equipo faltan poner los linkedins, y las imágenes si tenéis de mayor resolución mejor, así las puedo poner redondas y quedarán mejor. Este es un buen ejemplo para el equipo http://malabars.com/sobre-nosotros, y también me gustaría poner un texto de introducción al equipo, pero no se me ha ocurrido nada

Cualquier cambio lo haré mañana por la mañana

**Comment by meetsCode** [comment]
Correcciones.
Hay que quitar:
<<Como puede leerse en la prensa especializada la industria tiene 5 sistemas anti-copia encima de la mesa pero ninguno les satisface.>>

En Ventajas hay varias cosas que arreglar:
- [x] Hay que poner punto al final a cada frase.
- [x] Distribuïdores no lleva diéresis (en el último párrafo). 
- [x] En Escalabilidad no hay nada que hable de escalabilidad. Cambiar el título a "Data Analyst".
- [x] Incluir en el apartado Data Analyst al final: cumpliendo RGPD.
- [x] El párrafo "Bajo coste" debe quedar así: "Un sistema de servidores distribuido con un coste bajo  y alta escalabilidad." .  
- [x] El párrafo "Seguridad" debe quedar así: "Utilizamos tecnologias punteras. Nos inspiramos en Blockchain y Git para tener un sistema seguro"

Es muy importante este último punto para no generar falsas expectativas. 
Cuando este cambio esté hecho puedo anunciar la web.

Lo de "Ventajas" ha quedado tan chulo que yo no lo substituiría por el blog. El blog lo añadiremos como blog sin más.

Gracias. Buen trabajo.

**Comment by DataKatebet** [comment]
En el repositorio "diapositivas", branch "edición ppt infarma", he subido la ppt con la dirección web nueva para que la uses cuando quieras. Mantuve el http para que los ignorantes sepamos a golpe de vista que es una web.

**Comment by sia-x** [comment]
Ya he solucionado los problemas, también decir que he añadido los linkedins nuestros a la web, en el git de diapositivas abriré una issue para que se ponga mi LinkedIn en la presentación, y también colgare en aquel repositorio el logo que he hecho para la web por si lo usamos para otra cosa.
