### ISSUE TITLE
otras correcciones y aclaraciones

### ISSUE THREAD

**Issue by meetsCode** [meetsCode/meetsCode.github.io#2]
Hola, estos detalles creo que aún hay que cambiarlos:
Al comienzo de la página:
- [x] Fácil es con acento y 
- [x] anti-copia prefiero que vaya con guión. ¿Lorena puedes mirarme lo que dice la fundeu al respecto? Quiero ser apropiado. 

Creo que hay que crear un apartado que aclare quiénes somos... Quiero decir ¿TracBox es una empresa, es una startup, es una tecnología,....? Abriré un nuevo issue para discutir el texto y cuando lo tengamos claro lo incluimos.

Lorena: 
Cada Issue tiene su propio tema. Para cada tema hay que abrir un isssue nuevo. Así podemos asociar algunas versiones (commits) a determinados issue. 
Me refiero al siguiente mensaje que ha aparecido en el repositorio de la web:
"En el repositorio "diapositivas", branch "edición ppt infarma", he subido la ppt con la dirección web nueva para que la uses cuando quieras. Mantuve el http para que los ignorantes sepamos a golpe de vista que es una web."

**Comment by sia-x** [comment]
Copio del mail un texto que va en esta issue:

"""
Uso de guión según la RAE:
. Aunque normalmente los prefijos se unen directamente a la palabra base (antinatural, prerrevolucionario,etc.), cuando el prefijo precede a una sigla o a una palabra que comienza por mayúscula, se escribe guion intermedio: anti-OTAN, anti-Mussolini

Uso de guion segun fundeu:
Une un prefijo con la palabra a la que acompaña cuando esta empieza por mayúscula, es una sigla o un número: anti-OTAN, anti-Mussolini, sub-18, super-8

Tenemos un sistema "anticopia" por unanimidad. 
"""

Problemas solucionados
